version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: seu_banco_de_dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
